#!/usr/bin/env bash
# Create or update a PR with container image updates.
#
# Required env:
#   GH_TOKEN  - GitHub token for gh CLI
#   BRANCH    - branch name for the PR
#
# Reads: /tmp/pr_body.md (generated by check-image-updates.sh)

set -euo pipefail

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

EXISTING_PR=$(gh pr list --head "$BRANCH" --state open \
  --json number --jq '.[0].number // empty' 2>/dev/null || true)

git checkout -B "$BRANCH"
git add -u
git commit -m "chore: update container images"
git push --force origin "$BRANCH"

if [ -n "$EXISTING_PR" ]; then
  gh pr edit "$EXISTING_PR" --body-file /tmp/pr_body.md
  echo "Updated existing PR #$EXISTING_PR"
else
  gh pr create \
    --title "chore: update container images" \
    --body-file /tmp/pr_body.md
  echo "Created new PR"
fi
